name: My Second Workflow

on: push 

jobs: 
  print: 
    runs-on: ubuntu-latest

    steps:
     - name: Code Checkout Repo
       uses: actions/checkout@v5

     - name: checking the code 
       run: ls -l 