name: My Second Workflow

on: push 

jobs: 
  Build:
    runs-on: ubuntu-latest

    steps:
     - name: Code Checkout Repo
       uses: actions/checkout@v5

     - name: Building 
       run: echo "Building........"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Testing
        run: echo "Testing"

  deploy:
        runs-on: ubuntu-latest
          
        steps:
            - name: Deployment
              run: echo "Deploying........" 