name: My Second Workflow

on: push 

jobs: 
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [14, 16, 18]

    steps:
      - name: Code checkout Repo
        uses: actions/checkout@v5   

      - name: Setting up Node JS  ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
         node-version: ${{ matrix.node-version }}

      - name: Verifying the Nodejs Version
        run: node -v   


