name: My Second Workflow

on: push 

jobs: 
  Build:
    runs-on: ubuntu-latest

    steps:
     - name: Code Checkout Repo
       uses: actions/checkout@v5

     - name: Building 
       run: echo "Building........"

  test:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Testing
        run: |
          echo "Testing"
          sleep 10 

  deploy:
        runs-on: ubuntu-latest
        needs: test  

        steps:
            - name: Deployment
              run: | 
                echo "Deploying........" 
                sleep 5